version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - mynetwork
    entrypoint: ["/wait-for-postgres.sh", "postgres", "npm", "run", "start:dev"]
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

networks:
  mynetwork:
    driver: bridge
