import { Test, TestingModule } from '@nestjs/testing';
import { PeopleService } from './people.service';
import { Person } from './entities/person.entity';
import { Repository } from 'typeorm';
import { HashingServiceProtocol } from '../auth/hashing/hashing.service';
import { getRepositoryToken } from '@nestjs/typeorm';
import { CreatePersonDto } from './dto/create-person.dto';
import { ConflictException } from '@nestjs/common';
import { error } from 'console';

describe('PeopleService', () => {
  let service: PeopleService;
  let personRepository: Repository<Person>;
  let hashingServiceProtocol: HashingServiceProtocol;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        PeopleService,
        {
          provide: getRepositoryToken(Person),
          useValue: {
            create: jest.fn(),
            save: jest.fn(),
          },
        },
        {
          provide: HashingServiceProtocol,
          useValue: {
            hash: jest.fn(),
            compare: jest.fn(),
          },
        },
      ],
    }).compile();

    service = module.get<PeopleService>(PeopleService);
    personRepository = module.get<Repository<Person>>(
      getRepositoryToken(Person),
    );
    hashingServiceProtocol = module.get<HashingServiceProtocol>(
      HashingServiceProtocol,
    );
  });
  it('should be defined', () => {
    expect(service).toBeDefined();
  });
  describe('create', () => {
    it('should create a person', async () => {
      //Arrange
      // createPersonDto
      const createPersonDto: CreatePersonDto = {
        email: 'fabricio@email.com',
        name: 'Fabricio',
        password: '123456',
      };
      const passwordHash = 'PASSWORDHASH';
      const newPerson = {
        id: 1,
        name: createPersonDto.name,
        email: createPersonDto.email,
        passwordHash,
      };

      jest
        .spyOn(hashingServiceProtocol, 'hash')
        .mockResolvedValue(passwordHash);
      //Person returned to the personRepository.create is necessary in
      // personRepository.save. Let's to simulate this value
      jest.spyOn(personRepository, 'create').mockReturnValue(newPerson as any);

      //Act
      const result = await service.create(createPersonDto);

      //Assert
      // The method hashingServiceProtocol.hash was called with the password
      expect(hashingServiceProtocol.hash).toHaveBeenCalledWith(
        createPersonDto.password,
      );
      // Was the personRepository.create method called with the new person's data, including the passwordHash generated by hashingServiceProtocol.hash?
      expect(personRepository.create).toHaveBeenCalledWith({
        name: createPersonDto.name,
        email: createPersonDto.email,
        passwordHash: 'PASSWORDHASH',
      });
      // Did the personRepository.create method generate the passwordHash and use it when creating the new person?
      expect(personRepository.save).toHaveBeenCalledWith(newPerson);

      // Does the personRepository.create method return the newly created person?
      expect(result).toEqual(newPerson);
    });

    it('should throw an error if the person already exists with', async () => {
      jest.spyOn(personRepository, 'save').mockRejectedValue({
        code: '23505',
      });

      await expect(service.create({} as any)).rejects.toThrow(
        ConflictException,
      );
    });

    it('should throw an error if the person already exists with a generic error', async () => {
      jest
        .spyOn(personRepository, 'save')
        .mockRejectedValue(new Error('generic error'));

      await expect(service.create({} as any)).rejects.toThrow(Error);
    });
  });
});
